// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buyjnkznravowwtehxtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1eWpua3pucmF2b3d3dGVoeHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjg4MzIsImV4cCI6MjA2NTY0NDgzMn0.r3upkk9mHYb5m3S2llSqa5bLaT2lWYAbrLCjk3Ml2Ic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);