apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-deployment
  namespace: default
spec:
  replicas: 2 # Kept at 2 for resilience/load distribution
  selector:
    matchLabels:
      app: crash-app
  template:
    metadata:
      labels:
        app: crash-app
    spec:
      containers:
        - name: crash-container
          image: nginx:latest # Switched to Nginx for a functional web server
          ports:
            - containerPort: 80 # Expose Nginx's default port
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          livenessProbe: # Updated to check Nginx health
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe: # Added to ensure Nginx is ready to serve traffic
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
