apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-issue-demo
  labels:
    app: network-issue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-issue
  template:
    metadata:
      labels:
        app: network-issue
    spec:
      containers:
        - name: network-issue
          image: nicolaka/netshoot
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                # Simulate network issues for 30 seconds
                tc qdisc add dev eth0 root netem loss 80% delay 1000ms 2000ms
                echo "Network degraded"
                sleep 30
                
                # Fix network for 60 seconds
                tc qdisc del dev eth0 root
                echo "Network restored"
                sleep 60
              done
